"""initial schema: target, forecast, outcome

Revision ID: 6cce7a07f387
Revises: 
Create Date: 2026-06-07 02:31:51.922615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6cce7a07f387'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('target_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('support', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('forecast',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.target_id'], ),
    sa.PrimaryKeyConstraint('forecast_id'),
    sa.UniqueConstraint('target_id', 'source_id', 'as_of', name='uq_forecast_target_source_asof')
    )
    op.create_table('outcome',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('observed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.target_id'], ),
    sa.PrimaryKeyConstraint('target_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome')
    op.drop_table('forecast')
    op.drop_table('target')
    # ### end Alembic commands ###
